# Generated by Django 5.2.5 on 2025-08-29 09:42

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('cat_1', 'Art'), ('cat_2', 'Sciences'), ('cat_3', 'History'), ('cat_4', 'Natural History'), ('cat_5', 'Cultural'), ('cat_6', 'Children'), ('cat_7', 'Interactive')], default=['cat_1', 'cat_7'], max_length=41)),
                ('city', models.TextField()),
            ],
        ),
    ]
