# Generated by Django 5.2.5 on 2025-08-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finder', '0002_delete_museum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('category', models.TextField()),
                ('city', models.TextField()),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
    ]
