# Generated by Django 5.2.5 on 2025-09-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='category',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='museum',
            name='city',
            field=models.CharField(),
        ),
    ]
