# Generated by Django 5.2.5 on 2025-09-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
