# Generated by Django 5.2.5 on 2025-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='city',
            field=models.TextField(),
        ),
    ]
